apiVersion: v1
kind: ConfigMap
metadata:
  name: navalrivals-config
  namespace: navalrivals
data:
  FRONT_DOMAIN: "*"
  OPENTELEMETRY_TRACING_ENDPOINT: "http://172.20.0.1:4318/v1/traces"
  TRACING_PROBABILITY: "1.0"
  SPRING_PROFILES_ACTIVE: "dev"