apiVersion: v1
kind: Secret
metadata:
  name: navalrivals-secret
  namespace: navalrivals
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://172.20.0.1:5433/naval_rivals_db?useSSL=false&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SECRET_TOKEN_API: "naval-rivals-secret-token-4789e69a-8d59-4821"
  REDIS_HOST: "172.20.0.1"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  HOST_LOKI: "http://172.20.0.1:3100"