global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-naval-rivals-prod"
    scheme: https
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["naval-rivals-api.onrender.com"]
        labels:
          application: "api-naval-rivals"
          env: "production"

#  - job_name: "api-naval-rivals-local"
#    scheme: http
#    metrics_path: "/actuator/prometheus"
#    static_configs:
#      - targets: ["172.21.48.1:8080"]
#        labels:
#          application: "navalrivals-api"
#          env: "local"